# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

general:
  use_uvloop: true
  telemetry:
    tracing:
      weave:
        _type: weave
        project: "nat-ata"

functions:
  hardware_check:
    _type: hardware_check
    llm_name: tool_reasoning_llm
    offline_mode: true
  host_performance_check:
    _type: host_performance_check
    llm_name: tool_reasoning_llm
    offline_mode: true
  monitoring_process_check:
    _type: monitoring_process_check
    llm_name: tool_reasoning_llm
    offline_mode: true
  network_connectivity_check:
    _type: network_connectivity_check
    llm_name: tool_reasoning_llm
    offline_mode: true
  telemetry_metrics_host_heartbeat_check:
    _type: telemetry_metrics_host_heartbeat_check
    llm_name: tool_reasoning_llm
    offline_mode: true
    metrics_url: http://your-monitoring-server:9090 # Replace with your monitoring system URL if running in live mode
  telemetry_metrics_host_performance_check:
    _type: telemetry_metrics_host_performance_check
    llm_name: tool_reasoning_llm
    offline_mode: true
    metrics_url: http://your-monitoring-server:9090 # Replace with your monitoring system URL if running in live mode
  telemetry_metrics_analysis_agent:
    _type: telemetry_metrics_analysis_agent
    tool_names:
      - telemetry_metrics_host_heartbeat_check
      - telemetry_metrics_host_performance_check
    llm_name: telemetry_metrics_analysis_agent_llm
  maintenance_check:
    _type: maintenance_check
    llm_name: maintenance_check_llm
    static_data_path: examples/advanced_agents/alert_triage_agent/data/maintenance_static_dataset.csv
  categorizer:
    _type: categorizer
    llm_name: categorizer_llm

workflow:
  _type: alert_triage_agent
  tool_names:
    - hardware_check
    - host_performance_check
    - monitoring_process_check
    - network_connectivity_check
    - telemetry_metrics_analysis_agent
  llm_name: ata_agent_llm
  offline_mode: true
  # The below paths are only used if offline_mode is true
  offline_data_path: examples/advanced_agents/alert_triage_agent/data/offline_data.csv
  benign_fallback_data_path: examples/advanced_agents/alert_triage_agent/data/benign_fallback_offline_data.json

llms:
  ata_agent_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.2
    max_tokens: 2048

  tool_reasoning_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.2
    top_p: 0.7
    max_tokens: 2048

  telemetry_metrics_analysis_agent_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0
    max_tokens: 2048

  maintenance_check_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0
    max_tokens: 2048

  categorizer_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0
    max_tokens: 2048

  nim_rag_eval_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    max_tokens: 8

  nim_trajectory_eval_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    max_tokens: 1024

eval:
  general:
    output_dir: .tmp/nat/examples/advanced_agents/alert_triage_agent/output/llama_33/
    workflow_alias: alert_triage_agent_llama_33_70b
    dataset:
      _type: json
      # JSON representation of the offline CSV data (including just the alerts, the expected output, and the label)
      file_path: examples/advanced_agents/alert_triage_agent/data/offline_data.json
    profiler:
      base_metrics: true

  evaluators:
    rag_accuracy:
      _type: ragas
      metric: AnswerAccuracy
      llm_name: nim_rag_eval_llm
    classification_accuracy:
      _type: classification_accuracy
